program AziendaAlimentareERP;

uses
  Vcl.Forms,
  uFrmMain in 'uFrmMain.pas' {FrmMain},
  Vcl.Themes,
  Vcl.Styles,
  FireDAC.VCLUI.Wait,
  DbU in 'core\DbU.pas',
  GlobalU in 'core\GlobalU.pas',
  LoggerU in 'core\LoggerU.pas',
  uConfig in 'common\uConfig.pas',
  uFunzioni in 'common\uFunzioni.pas',
  uLog in 'common\uLog.pas',
  uType in 'common\uType.pas',
  uControllerFornitori in 'controllers\uControllerFornitori.pas',
  uWebModule in 'uWebModule.pas' {WebModule1: TWebModule},
  uCORSController in 'controllers\uCORSController.pas',
  uControllerClienti in 'controllers\uControllerClienti.pas',
  uControllerMateriePrime in 'controllers\uControllerMateriePrime.pas',
  uServiziGiacenza in 'services\uServiziGiacenza.pas',
  uModelConsumoProduzioneProdottoFinito in 'models\uModelConsumoProduzioneProdottoFinito.pas',
  uModelConsumoProduzioneSemilavorato in 'models\uModelConsumoProduzioneSemilavorato.pas',
  uModelLottoSemilavorato in 'models\uModelLottoSemilavorato.pas',
  uModelLottoMateriaPrima in 'models\uModelLottoMateriaPrima.pas',
  uModelNonConformita in 'models\uModelNonConformita.pas',
  uModelRicettaSemilavorato in 'models\uModelRicettaSemilavorato.pas',
  uModelRicettaProdottoFinito in 'models\uModelRicettaProdottoFinito.pas',
  uModelOrdineVenditaRiga in 'models\uModelOrdineVenditaRiga.pas',
  uModelOrdineVendita in 'models\uModelOrdineVendita.pas',
  uModelOrdineFornitoreRiga in 'models\uModelOrdineFornitoreRiga.pas',
  uModelOrdineFornitore in 'models\uModelOrdineFornitore.pas',
  uModelRicettaProdottoFinitoRiga in 'models\uModelRicettaProdottoFinitoRiga.pas',
  uModelRicettaSemilavoratoRiga in 'models\uModelRicettaSemilavoratoRiga.pas',
  uModelDDTUscitaRiga in 'models\uModelDDTUscitaRiga.pas',
  uModelDDTUscita in 'models\uModelDDTUscita.pas',
  uModelDDTEntrataRiga in 'models\uModelDDTEntrataRiga.pas',
  uModelDDTEntrata in 'models\uModelDDTEntrata.pas',
  uModelLottoProdottoFinito in 'models\uModelLottoProdottoFinito.pas',
  uModelProdottoFinito in 'models\uModelProdottoFinito.pas',
  uModelSemilavorato in 'models\uModelSemilavorato.pas',
  uModelMateriaPrima in 'models\uModelMateriaPrima.pas',
  uModelAllergene in 'models\uModelAllergene.pas',
  uModelCliente in 'models\uModelCliente.pas',
  uModelStabilimento in 'models\uModelStabilimento.pas',
  uModelFornitore in 'models\uModelFornitore.pas',
  uServiziRitiroRichiamo in 'services\uServiziRitiroRichiamo.pas',
  uServiziRicette in 'services\uServiziRicette.pas',
  uEsportazioneCSV in 'services\uEsportazioneCSV.pas',
  uEsportazionePDF in 'services\uEsportazionePDF.pas',
  uVenditeToolProvider in 'agente_ai\tool\uVenditeToolProvider.pas',
  uClientiToolProvider in 'agente_ai\tool\uClientiToolProvider.pas',
  uEmailToolProvider in 'agente_ai\tool\uEmailToolProvider.pas',
  uFilesToolsProvider in 'agente_ai\tool\uFilesToolsProvider.pas',
  uServiziVendite in 'services\uServiziVendite.pas',
  Service.EmailServer in 'services\Service.EmailServer.pas',
  uServiziModelliEmail in 'services\uServiziModelliEmail.pas',
  AIAgentControllerU in 'controllers\AIAgentControllerU.pas',
  uServiziDashboard in 'services\uServiziDashboard.pas',
  uControllerDashboard in 'controllers\uControllerDashboard.pas',
  uServiziOrdiniVendita in 'services\uServiziOrdiniVendita.pas',
  uControllerOrdiniVendita in 'controllers\uControllerOrdiniVendita.pas',
  uControllerProdottiFiniti in 'controllers\uControllerProdottiFiniti.pas',
  uServiziAgente in 'agente_ai\1_turno\uServiziAgente.pas',
  uMCPBridge in 'agente_ai\5_esecuzione\uMCPBridge.pas',
  uRegistroViste in 'common\uRegistroViste.pas',
  uNavigazioneToolProvider in 'agente_ai\tool\uNavigazioneToolProvider.pas',
  uRicetteToolProvider in 'agente_ai\tool\uRicetteToolProvider.pas',
  uControllerRicette in 'controllers\uControllerRicette.pas',
  uControllerSemilavorati in 'controllers\uControllerSemilavorati.pas',
  uServiziLotti in 'services\uServiziLotti.pas',
  uControllerLottiMateriePrime in 'controllers\uControllerLottiMateriePrime.pas',
  uControllerLottiSemilavorati in 'controllers\uControllerLottiSemilavorati.pas',
  uControllerLottiProdottiFiniti in 'controllers\uControllerLottiProdottiFiniti.pas',
  uServiziTracciabilita in 'services\uServiziTracciabilita.pas',
  uControllerTracciabilita in 'controllers\uControllerTracciabilita.pas',
  uControllerEmail in 'controllers\uControllerEmail.pas',
  uRegistroProviderMCP in 'agente_ai\tool\uRegistroProviderMCP.pas',
  uContrattiTool in 'agente_ai\tool\uContrattiTool.pas',
  uCatalogoTool in 'agente_ai\tool\uCatalogoTool.pas',
  uServizioEmbedding in 'agente_ai\3_scelta_tool\uServizioEmbedding.pas',
  uIndiceEmbeddingTool in 'agente_ai\3_scelta_tool\uIndiceEmbeddingTool.pas',
  uFrasiEsempioTool in 'agente_ai\3_scelta_tool\uFrasiEsempioTool.pas',
  TextFileWriterU in 'common\TextFileWriterU.pas',
  uRitiroRichiamoToolProvider in 'agente_ai\tool\uRitiroRichiamoToolProvider.pas',
  uClientLLM in 'agente_ai\modello\uClientLLM.pas',
  uSchemaJSON in 'agente_ai\4_controlli\uSchemaJSON.pas',
  uRiferimentiPiano in 'agente_ai\4_controlli\uRiferimentiPiano.pas',
  uPromptPianificatore in 'agente_ai\2_piano\uPromptPianificatore.pas',
  uPianificatore in 'agente_ai\2_piano\uPianificatore.pas',
  uRetrieverPiano in 'agente_ai\3_scelta_tool\uRetrieverPiano.pas',
  uValidatorePiano in 'agente_ai\4_controlli\uValidatorePiano.pas',
  uEsecutorePiano in 'agente_ai\5_esecuzione\uEsecutorePiano.pas',
  uStoricoTurni in 'agente_ai\1_turno\uStoricoTurni.pas',
  uSintesiRisposta in 'agente_ai\6_risposta\uSintesiRisposta.pas',
  uTurnoPianificato in 'agente_ai\1_turno\uTurnoPianificato.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('Windows Modern Dark');
  Application.CreateForm(TFrmMain, FrmMain);
  Application.Run;
end.
